"""
================================================================================
 I-SCEET — XLSX Builder
 File: orchestrator/xlsx_builder.py
================================================================================
 Parses M4/M5/M6 LLM text output → generates Excel .xlsx files
 M4 → SUTC-0xx.xlsx  (Software Unit Test Cases)
 M5 → SVTC-0xx.xlsx  (Software Verification Test Cases)
 M6 → TM-0xx.xlsx    (Traceability Matrix)
================================================================================
"""

import os
import re
from datetime import datetime

try:
    import openpyxl
    from openpyxl.styles import (
        PatternFill, Font, Alignment, Border, Side, GradientFill
    )
    from openpyxl.utils import get_column_letter
except ImportError:
    raise ImportError("openpyxl required: pip install openpyxl")


# ── STYLE CONSTANTS ───────────────────────────────────────────────────────────
BLUE_FILL  = PatternFill("solid", fgColor="1F3864")
MID_FILL   = PatternFill("solid", fgColor="2E75B6")
GRAY_FILL  = PatternFill("solid", fgColor="F2F2F2")
WHITE_FILL = PatternFill("solid", fgColor="FFFFFF")
CORAL_FILL = PatternFill("solid", fgColor="FFE0D6")
GREEN_FILL = PatternFill("solid", fgColor="D6FFE0")

WHITE_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=10)
BLUE_FONT  = Font(name="Arial", bold=True, color="1F3864", size=10)
BODY_FONT  = Font(name="Arial", size=10)
BOLD_FONT  = Font(name="Arial", bold=True, size=10)

THIN_BORDER = Border(
    left=Side(style='thin', color='CCCCCC'),
    right=Side(style='thin', color='CCCCCC'),
    top=Side(style='thin', color='CCCCCC'),
    bottom=Side(style='thin', color='CCCCCC'),
)
CENTER = Alignment(horizontal='center', vertical='center', wrap_text=True)
LEFT   = Alignment(horizontal='left',   vertical='top',    wrap_text=True)


def _style_header_row(ws, row_num: int, col_count: int):
    """Apply blue header styling to a row."""
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.fill   = BLUE_FILL
        cell.font   = WHITE_FONT
        cell.alignment = CENTER
        cell.border = THIN_BORDER


def _style_data_row(ws, row_num: int, col_count: int, alternate: bool = False):
    """Apply data row styling."""
    for col in range(1, col_count + 1):
        cell = ws.cell(row=row_num, column=col)
        cell.fill   = GRAY_FILL if alternate else WHITE_FILL
        cell.font   = BODY_FONT
        cell.alignment = LEFT
        cell.border = THIN_BORDER


def _add_cover_sheet(wb, title: str, doc_id: str, version: str,
                     module: str, model: str):
    """Add a cover/info sheet to the workbook."""
    ws = wb.active
    ws.title = "INFO"

    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 55

    rows = [
        ("Document", title),
        ("Document ID", doc_id),
        ("Version", version),
        ("Status", "DRAFT"),
        ("Date", datetime.now().strftime("%Y-%m-%d")),
        ("Generated by", f"{module} — {model}"),
        ("Project", "I-SCEET"),
        ("Institution", "Capgemini Engineering / ESPRIT"),
        ("Standard", "RTCA DO-178C"),
    ]
    for i, (key, val) in enumerate(rows, 1):
        ws.cell(row=i, column=1, value=key).font = BOLD_FONT
        ws.cell(row=i, column=1).fill = BLUE_FILL if i == 1 else GRAY_FILL
        ws.cell(row=i, column=1).font = WHITE_FONT if i == 1 else BOLD_FONT
        ws.cell(row=i, column=1).alignment = LEFT
        ws.cell(row=i, column=2, value=val).font = BODY_FONT
        ws.cell(row=i, column=2).alignment = LEFT

    for r in range(1, len(rows) + 1):
        ws.row_dimensions[r].height = 18


# ── PARSERS ───────────────────────────────────────────────────────────────────
def _parse_test_cases(text: str, id_prefix: str) -> list:
    """Parse test case blocks (SUTC or SVTC format)."""
    cases = []

    # Match blocks delimited by ---
    blocks = re.findall(r'---\s*(TC-ID:.*?(?:Safety-Note:|Method:).*?)\s*---',
                        text, re.DOTALL)
    if not blocks:
        # Fallback: looser pattern
        blocks = re.findall(
            r'TC-ID:\s*.+?(?=TC-ID:|\Z)', text, re.DOTALL
        )

    for block in blocks:
        tc = {}
        fields = ['TC-ID', 'Title', 'LLR-Ref', 'HLR-Ref', 'Objective',
                  'Test-Type', 'Preconditions', 'Test-Steps', 'Inputs',
                  'Expected', 'Pass-Criteria', 'Fail-Criteria', 'Coverage',
                  'Method', 'Safety-Note']
        for field in fields:
            m = re.search(rf'{re.escape(field)}:\s*(.+?)(?=\n[A-Z]|\Z)',
                          block, re.DOTALL)
            tc[field] = m.group(1).strip() if m else ''
        if tc.get('TC-ID'):
            cases.append(tc)

    return cases


def _parse_traceability(text: str) -> dict:
    """Parse M6 traceability output into forward/backward/gaps."""
    result = {'forward': [], 'backward': [], 'gaps': [], 'summary': ''}

    # Forward traceability table rows
    fwd = re.findall(
        r'\|\s*([A-Z]+-[A-Za-z0-9-]+)\s*\|\s*([A-Z]+-[A-Za-z0-9-]+)\s*\|'
        r'\s*([A-Z]+-[A-Za-z0-9-]*)\s*\|\s*([^\|]+)\|\s*([A-Z]+-[A-Za-z0-9-]*)\s*'
        r'\|\s*([A-Z]+-[A-Za-z0-9-]*)\s*\|\s*([A-Z]+)\s*\|',
        text
    )
    for row in fwd:
        result['forward'].append({
            'PDS-ID': row[0], 'HLR-ID': row[1], 'LLR-ID': row[2],
            'Code': row[3].strip(), 'LLT-ID': row[4], 'HLT-ID': row[5],
            'Status': row[6]
        })

    # Gaps
    gap_section = re.search(r'SECTION 3.*?SECTION 4', text, re.DOTALL | re.IGNORECASE)
    if gap_section:
        result['gaps'] = [l.strip() for l in gap_section.group().split('\n')
                          if l.strip() and not l.strip().startswith('SECTION')]

    # Summary
    summ = re.search(r'CERTIFICATION READINESS:.+', text, re.IGNORECASE)
    result['summary'] = summ.group().strip() if summ else ''

    return result


# ── MAIN BUILDERS ─────────────────────────────────────────────────────────────
def build_sutc(m4_output: str, output_path: str, version: str = "1.0") -> str:
    """Build SUTC-0xx.xlsx from M4 output."""
    wb = openpyxl.Workbook()
    _add_cover_sheet(wb, "Software Unit Test Cases", "SUTC-0xx",
                     version, "M4", "Gemma3 27B")

    ws = wb.create_sheet("SUTC")
    ws.title = "SUTC"

    headers = ['TC-ID', 'Title', 'LLR-Ref', 'Objective', 'Preconditions',
               'Inputs', 'Expected', 'Pass-Criteria', 'Fail-Criteria',
               'Coverage', 'Method']
    col_widths = [15, 30, 15, 40, 30, 30, 40, 30, 30, 25, 15]

    for col, (h, w) in enumerate(zip(headers, col_widths), 1):
        ws.cell(row=1, column=col, value=h)
        ws.column_dimensions[get_column_letter(col)].width = w
    _style_header_row(ws, 1, len(headers))
    ws.row_dimensions[1].height = 20

    cases = _parse_test_cases(m4_output, 'LLT')
    for i, tc in enumerate(cases, 2):
        row_vals = [
            tc.get('TC-ID', ''), tc.get('Title', ''), tc.get('LLR-Ref', ''),
            tc.get('Objective', ''), tc.get('Preconditions', ''),
            tc.get('Inputs', ''), tc.get('Expected', ''),
            tc.get('Pass-Criteria', ''), tc.get('Fail-Criteria', ''),
            tc.get('Coverage', ''), tc.get('Method', ''),
        ]
        for col, val in enumerate(row_vals, 1):
            ws.cell(row=i, column=col, value=val)
        _style_data_row(ws, i, len(headers), alternate=(i % 2 == 0))
        ws.row_dimensions[i].height = 40

    # Stats
    ws_stats = wb.create_sheet("Coverage Summary")
    ws_stats['A1'] = "Total LLT Cases"
    ws_stats['B1'] = len(cases)
    ws_stats['A2'] = "Normal cases"
    ws_stats['B2'] = sum(1 for c in cases if 'normal' in c.get('Title','').lower())
    ws_stats['A3'] = "Boundary cases"
    ws_stats['B3'] = sum(1 for c in cases if 'boundary' in c.get('Title','').lower()
                                           or 'edge' in c.get('Title','').lower())
    ws_stats['A4'] = "Error cases"
    ws_stats['B4'] = sum(1 for c in cases if 'error' in c.get('Title','').lower()
                                          or 'fail' in c.get('Title','').lower())

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    wb.save(output_path)
    return output_path


def build_svtc(m5_output: str, output_path: str, version: str = "1.0") -> str:
    """Build SVTC-0xx.xlsx from M5 output."""
    wb = openpyxl.Workbook()
    _add_cover_sheet(wb, "Software Verification Test Cases", "SVTC-0xx",
                     version, "M5", "DeepSeek-R1-Distill 32B")

    ws = wb.create_sheet("SVTC")
    ws.title = "SVTC"

    headers = ['TC-ID', 'Title', 'HLR-Ref', 'Objective', 'Test-Type',
               'Preconditions', 'Test-Steps', 'Expected',
               'Pass-Criteria', 'Fail-Criteria', 'Method', 'Safety-Note']
    col_widths = [15, 30, 15, 40, 15, 30, 50, 40, 30, 30, 15, 30]

    for col, (h, w) in enumerate(zip(headers, col_widths), 1):
        ws.cell(row=1, column=col, value=h)
        ws.column_dimensions[get_column_letter(col)].width = w
    _style_header_row(ws, 1, len(headers))

    cases = _parse_test_cases(m5_output, 'HLT')
    for i, tc in enumerate(cases, 2):
        row_vals = [
            tc.get('TC-ID', ''), tc.get('Title', ''), tc.get('HLR-Ref', ''),
            tc.get('Objective', ''), tc.get('Test-Type', ''),
            tc.get('Preconditions', ''), tc.get('Test-Steps', ''),
            tc.get('Expected', ''), tc.get('Pass-Criteria', ''),
            tc.get('Fail-Criteria', ''), tc.get('Method', ''),
            tc.get('Safety-Note', ''),
        ]
        for col, val in enumerate(row_vals, 1):
            ws.cell(row=i, column=col, value=val)
        _style_data_row(ws, i, len(headers), alternate=(i % 2 == 0))
        ws.row_dimensions[i].height = 50

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    wb.save(output_path)
    return output_path


def build_tm(m6_output: str, output_path: str, version: str = "1.0") -> str:
    """Build TM-0xx.xlsx from M6 traceability output."""
    wb = openpyxl.Workbook()
    _add_cover_sheet(wb, "Traceability Matrix", "TM-0xx",
                     version, "M6", "Phi-4 14B")

    parsed = _parse_traceability(m6_output)

    # Sheet 1 — Forward traceability
    ws_fwd = wb.create_sheet("Forward Traceability")
    fwd_headers = ['PDS-ID', 'HLR-ID', 'LLR-ID', 'Code Function',
                   'LLT-ID (SUTC)', 'HLT-ID (SVTC)', 'Status']
    fwd_widths   = [15, 20, 20, 30, 20, 20, 15]

    for col, (h, w) in enumerate(zip(fwd_headers, fwd_widths), 1):
        ws_fwd.cell(row=1, column=col, value=h)
        ws_fwd.column_dimensions[get_column_letter(col)].width = w
    _style_header_row(ws_fwd, 1, len(fwd_headers))

    for i, row in enumerate(parsed['forward'], 2):
        vals = [row.get('PDS-ID',''), row.get('HLR-ID',''), row.get('LLR-ID',''),
                row.get('Code',''), row.get('LLT-ID',''), row.get('HLT-ID',''),
                row.get('Status','')]
        for col, val in enumerate(vals, 1):
            cell = ws_fwd.cell(row=i, column=col, value=val)
            cell.border = THIN_BORDER
            cell.font = BODY_FONT
            if vals[-1] == 'GAP':
                cell.fill = CORAL_FILL
            elif vals[-1] == 'COMPLETE':
                cell.fill = GREEN_FILL
            else:
                cell.fill = GRAY_FILL if i % 2 == 0 else WHITE_FILL

    # Sheet 2 — Raw M6 output (full text for review)
    ws_raw = wb.create_sheet("Full M6 Output")
    ws_raw.column_dimensions['A'].width = 150
    for i, line in enumerate(m6_output.split('\n')[:500], 1):
        ws_raw.cell(row=i, column=1, value=line).font = Font(name="Courier New", size=9)

    # Sheet 3 — Gaps
    ws_gaps = wb.create_sheet("Traceability Gaps")
    ws_gaps.cell(row=1, column=1, value="Traceability Gap").font = WHITE_FONT
    ws_gaps.cell(row=1, column=1).fill = BLUE_FILL
    ws_gaps.column_dimensions['A'].width = 100
    for i, gap in enumerate(parsed['gaps'], 2):
        ws_gaps.cell(row=i, column=1, value=gap)
        ws_gaps.cell(row=i, column=1).fill = CORAL_FILL
        ws_gaps.cell(row=i, column=1).font = BODY_FONT

    # Sheet 4 — Summary
    ws_sum = wb.create_sheet("Coverage Summary")
    summary_data = [
        ("Metric", "Value"),
        ("Total forward trace rows", len(parsed['forward'])),
        ("COMPLETE links", sum(1 for r in parsed['forward'] if r.get('Status') == 'COMPLETE')),
        ("PARTIAL links", sum(1 for r in parsed['forward'] if r.get('Status') == 'PARTIAL')),
        ("GAP links", sum(1 for r in parsed['forward'] if r.get('Status') == 'GAP')),
        ("Traceability gaps found", len(parsed['gaps'])),
        ("Certification readiness", parsed.get('summary', 'See Full M6 Output sheet')),
    ]
    for i, (k, v) in enumerate(summary_data, 1):
        ws_sum.cell(row=i, column=1, value=k).font = BOLD_FONT
        ws_sum.cell(row=i, column=1).fill = BLUE_FILL if i == 1 else GRAY_FILL
        ws_sum.cell(row=i, column=1).font = WHITE_FONT if i == 1 else BOLD_FONT
        ws_sum.cell(row=i, column=2, value=str(v)).font = BODY_FONT
        ws_sum.column_dimensions['A'].width = 35
        ws_sum.column_dimensions['B'].width = 60

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    wb.save(output_path)
    return output_path
